/*
Welcome to the 60fps project! Your goal is to make Cam's Pizzeria website run
jank-free at 60 frames per second.

There are two major issues in this code that lead to sub-60fps performance. Can
you spot and fix both?


Built into the code, you'll find a few instances of the User Timing API
(window.performance), which will be console.log()ing frame rate data into the
browser console. To learn more about User Timing API, check out:
http://www.html5rocks.com/en/tutorials/webperformance/usertiming/

Creator:
Cameron Pittman, Udacity Course Developer
cameron *at* udacity *dot* com
*/
/*Creates the Web Worker*/
var workers = new Worker("js/workers.js")

/*@function
 * Gets information from workers to create the elements
  that contains the pizza name and ingrtedients*/
workers.onmessage = function(e){

  var pizzaName  = createElem("h4");
  pizzaName.innerHTML = e.data.title
  var pizzaIngredients = createElem("ul");
  pizzaIngredients.innerHTML = e.data.pizza
  var pizzasDiv = document.getElementById("randomPizzas");
  pizzasDiv.appendChild(pizzaElementGenerator(pizzaName, pizzaIngredients));
}

/** @function pizzaElementGenerator
  * @param {string} pizzaname - The name of the pizza generated by the workers.
  * @param {string} pizzaingredient - The ingredients list of the pizza generated by the workers.
  * @returns {DOM element} DOM element for each pizza.
*/
Called from a for loop
var pizzaElementGenerator = function(pizzaname, pizzaingredients) {
  var pizzaContainer,             // contains pizza title, image and list of ingredients
      pizzaImageContainer,        // contains the pizza image
      pizzaImage,                 // the pizza image itself
      pizzaDescriptionContainer,  // contains the pizza title and list of ingredients

  pizzaContainer = createElem("div");
  pizzaImageContainer = createElem("div");
  pizzaImage = createElem("img");
  pizzaDescriptionContainer = createElem("div");
  pizzaContainer.classList.add("randomPizzaContainer");
  pizzaContainer.style.width = "33.33%";
  pizzaContainer.style.height = "325px";
  pizzaContainer.id = "pizza" + pizzaingredients;
  pizzaImageContainer.classList.add("col-md-6");
  pizzaImage.src = "https://s3-us-west-2.amazonaws.com/vaneprojects/Project4Udacity/pizza3.png";
  pizzaImage.classList.add("img-responsive");
  pizzaImageContainer.appendChild(pizzaImage);
  pizzaContainer.appendChild(pizzaImageContainer);
  pizzaDescriptionContainer.classList.add("col-md-6");
  pizzaDescriptionContainer.appendChild(pizzaname);
  pizzaDescriptionContainer.appendChild(pizzaingredients);
  pizzaContainer.appendChild(pizzaDescriptionContainer);

  return pizzaContainer;
};

// resizePizzas(size) is called when the slider in the "Our Pizzas" section of the website moves.
var resizePizzas = function(size) {

  window.performance.mark("mark_start_resize");   // User Timing API function

  // Changes the value for the size of the pizza above the slider
  function changeSliderLabel(size) {
    switch(size) {
      case "1":
        document.querySelector("#pizzaSize").innerHTML = "Small";
        return;
      case "2":
        document.querySelector("#pizzaSize").innerHTML = "Medium";
        return;
      case "3":
        document.querySelector("#pizzaSize").innerHTML = "Large";
        return;
      default:
        console.log("bug in changeSliderLabel");
    }
  }

  changeSliderLabel(size);

  var newwidth;

    // Changes the slider value to a percent width
  function changePizzaSizes(size) {

    switch(size) {
      case "1":
       newwidth = 25;
       break
      case "2":
        newwidth = 33;
        break
      case "3":
        newwidth = 50;
        break
      default:
        console.log("bug in sizeSwitcher");

    }

    var pizzaBoxes = document.querySelectorAll(".randomPizzaContainer");

    for (var i = 0; i < 100; i++) {

      pizzaBoxes[i].style.width = newwidth + "%";
    }
  }

  changePizzaSizes(size);


  // User Timing API is awesome
  window.performance.mark("mark_end_resize");
  window.performance.measure("measure_pizza_resize", "mark_start_resize", "mark_end_resize");
  var timeToResize = window.performance.getEntriesByName("measure_pizza_resize");
  console.log("Time to resize pizzas: " + timeToResize[timeToResize.length-1].duration + "ms");
};

window.performance.mark("mark_start_generating"); // collect timing data


// User Timing API again. These measurements tell you how long it took to generate the initial pizzas
window.performance.mark("mark_end_generating");
window.performance.measure("measure_pizza_generation", "mark_start_generating", "mark_end_generating");
var timeToGenerate = window.performance.getEntriesByName("measure_pizza_generation");
console.log("Time to generate pizzas on load: " + timeToGenerate[0].duration + "ms");

// Iterator for number of times the pizzas in the background have scrolled.
// Used by updatePositions() to decide when to log the average time per frame
var frame = 0;

// Logs the average amount of time per 10 frames needed to move the sliding background pizzas on scroll.
function logAverageFrame(times) {   // times is the array of User Timing measurements from updatePositions()
  var numberOfEntries = times.length;
  var sum = 0;
  for (var i = numberOfEntries - 1; i > numberOfEntries - 11; i--) {
    sum = sum + times[i].duration;
  }
  console.log("Average scripting time to generate last 10 frames: " + sum / 10 + "ms");
}

function createElem(htmlElement){

  var elem = document.createElement(htmlElement);
  return elem
}

  var cols = 8;
  var s = 256;
  var leftPosition = [100, 356, 612, 868, 1124, 1380, 1636, 1892];

window.onload = function(){

  for (var i = 0; i < 40; i++) {
    var elem = createElem('img');
    elem.className = 'mover';
    elem.src = "https://s3-us-west-2.amazonaws.com/vaneprojects/Project4Udacity/pizzaBackground.png";
    elem.style.height = "100px";
    elem.style.width = "73.333px";
    elem.style.left = leftPosition[i % cols]+ "px"
    elem.style.transform = "translateX("+0 +"px)"  ;
    elem.style.top = (Math.floor(i / cols) * s) + 'px';
    document.querySelector("#movingPizzas1").appendChild(elem);
  }
}

var latestKnownScrollY = 0,
    ticking = false;
window.addEventListener('scroll', onScroll);

function onScroll (){
  latestKnownScrollY = window.scrollY;
  requestTick();
}

function requestTick() {
  if(!ticking) {
    requestAnimationFrame(update);
  }
  ticking = true;
}

function update() {
  ticking = false;
  frame++;
 window.performance.mark("mark_start_frame");

  var items = document.querySelectorAll('.mover');
  var itemsLength= items.length;

  for (var i = 0; i < itemsLength; i++) {
    var phase = Math.sin((latestKnownScrollY / 1250) + (i % 5));
    items[i].style.transform = "translateX("+(100 * phase)+"px)"
  }

  window.performance.mark("mark_end_frame");
  window.performance.measure("measure_frame_duration", "mark_start_frame", "mark_end_frame");

  if (frame % 10 === 0) {
    var timesToUpdatePosition = window.performance.getEntriesByName("measure_frame_duration");
    logAverageFrame(timesToUpdatePosition);
  }

}
update()



